name: HelloWorld
on:
  push:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - run: javac HelloWorld.java
      - run: java HelloWorld